### ISSUE TITLE
[Todo] 개발 외 과제

### ISSUE THREAD

**Issue by seongbinLim** [seongbinLim/nhn_basecamp#4]
- [ ] 이슈 템플릿 만들어보기
- [x] 이슈 label 달아보기
- [x] 이슈 마일드스톤 달아보기
- [x] 깃블로그 개설하기
- [x] 깃블로그 이미지 올려보기
- [x] 깃블로그에 소감문 작성하기

**Comment by seongbinLim** [comment]
이슈 템플릿 commit 버튼 활성화 안됨 -> 확인 필요
